services:
  app_proxy:
    environment:
      APP_HOST: pleb-pool-ui_server_1
      APP_PORT: 80

  server:
    image: ntheile/pleb-pool-ui:latest@sha256:617a21b49d0816ce8a33aed65a68a5977845f7ad92622a7695e028143d643b7c
    restart: on-failure
    environment:
      API_URL: ${API_URL:-https://api.plebpool.com}
      STRATUM_URL: ${STRATUM_URL:-plebpool.com:2018}
      PRODUCTION: ${PRODUCTION:-true}
